// The Android+iOS half of the `mobile.rs`/`desktop.rs` split described in
// `lib.rs`. This file's job is narrow: get a handle to the real native
// plugin class -- Kotlin's `NativeMapPlugin` (`android/src/main/java/
// .../NativeMapPlugin.kt`) or Swift's `NativeMapPlugin`
// (`ios/Sources/NativeMapPlugin.swift`) -- and expose Rust methods that
// call into whichever one this build actually is. None of the actual map
// logic lives here -- it's all on the Kotlin/Swift side, and once
// `init()` below has picked the right one, `NativeMap<R>`'s methods
// don't need to know which platform they're actually talking to; both
// native sides implement the exact same set of command names.
use serde::de::DeserializeOwned;
use tauri::{
    plugin::{PluginApi, PluginHandle},
    AppHandle, Runtime,
};

use crate::models::*;
use crate::Result;

// iOS plugins are a compiled Swift *library*, not something Rust can
// look up by name/class the way `register_android_plugin` does for the
// JVM below -- instead the Swift side exports a C function
// (`@_cdecl("init_plugin_native_map")` in the .swift file) that
// constructs and returns the plugin instance, and this macro generates
// the Rust-side `extern "C"` declaration matching that exact symbol name
// so `register_ios_plugin` (in `init`, below) can call it. Only compiled
// at all when actually targeting iOS -- meaningless (and not even valid)
// on Android, hence its own `#[cfg]`.
#[cfg(target_os = "ios")]
tauri::ios_plugin_binding!(init_plugin_native_map);

// Called once from `lib.rs`'s `init()` (via `mobile::init(app, api)`)
// when the app starts. `PluginApi` is Tauri's handle to "the mobile side
// of this specific plugin" -- exactly one of the two branches below
// actually compiles, picked by `target_os` the same way `mobile.rs`
// itself is picked by `#[cfg(mobile)]` in `lib.rs`:
//   - `register_android_plugin` looks up the Kotlin class by its fully-
//     qualified name + class name (matching the `package`/`class
//     NativeMapPlugin` declared in the .kt file) at runtime, through
//     the JVM.
//   - `register_ios_plugin` instead takes the `init_plugin_native_map`
//     function generated by the macro above -- no runtime name lookup,
//     it's resolved at link time since Swift/Rust are both compiled
//     native code on iOS.
// Either way, the result is the same kind of `PluginHandle` that can
// send commands to whichever native instance got created.
pub fn init<R: Runtime, C: DeserializeOwned>(
    _app: &AppHandle<R>,
    api: PluginApi<R, C>,
) -> crate::Result<NativeMap<R>> {
    #[cfg(target_os = "android")]
    let handle = api.register_android_plugin("me.fern.rumad2.nativemap", "NativeMapPlugin")?;
    #[cfg(target_os = "ios")]
    let handle = api.register_ios_plugin(init_plugin_native_map)?;
    Ok(NativeMap(handle))
}

/// Handle to the native `NativeMapPlugin` (Kotlin on Android, Swift on
/// iOS) -- each method is a thin wrapper over `run_mobile_plugin`,
/// mirroring the `@Command`/`@objc` methods on whichever native side
/// this build actually has one-for-one.
pub struct NativeMap<R: Runtime>(PluginHandle<R>);

impl<R: Runtime> NativeMap<R> {
    // `run_mobile_plugin(commandName, payload)` is the actual RPC call:
    // it serializes `payload` to JSON, sends it across to the native
    // plugin instance held by `self.0`, and blocks until that side calls
    // `invoke.resolve(...)`/`invoke.reject(...)` (see `@Command fun
    // createMap(invoke: Invoke)` in the Kotlin file, or `@objc public
    // func createMap(_ invoke: Invoke)` in the Swift one) -- the string
    // here ("createMap") has to match that method's name exactly on
    // *both* platforms, that's the only thing connecting the two sides.
    // There's no compile-time check tying "createMap" to either native
    // method, unlike the Rust-side command names in `commands.rs`, which
    // the compiler does check against `invoke_handler!`.
    pub fn create_map(&self, payload: CreateMapArgs) -> Result<()> {
        self.0.run_mobile_plugin("createMap", payload).map_err(Into::into)
    }

    pub fn update_frame(&self, payload: UpdateFrameArgs) -> Result<()> {
        self.0.run_mobile_plugin("updateFrame", payload).map_err(Into::into)
    }

    pub fn set_camera(&self, payload: SetCameraArgs) -> Result<()> {
        self.0.run_mobile_plugin("setCamera", payload).map_err(Into::into)
    }

    pub fn set_marker(&self, payload: SetMarkerArgs) -> Result<()> {
        self.0.run_mobile_plugin("setMarker", payload).map_err(Into::into)
    }

    // `()` as the payload -- `dispose` takes no arguments on either side
    // (`Invoke` on the native side just won't have any args to parse).
    pub fn dispose(&self) -> Result<()> {
        self.0.run_mobile_plugin("dispose", ()).map_err(Into::into)
    }
}
